const test = require("node:test");
const assert = require("node:assert/strict");

const load = () => import("../../src/helpers/notesRegenerationPolicy.js");

test("the setting being off stops everything", async () => {
  const { shouldRegenerateNotes } = await load();

  assert.deepEqual(
    shouldRegenerateNotes({
      enabled: false,
      enhancedContent: "notes",
      generatedHash: "h",
      hashOf: () => "h",
    }),
    { regenerate: false, reason: "disabled" }
  );
});

test("empty notes are never generated by a rename", async () => {
  const { shouldRegenerateNotes } = await load();

  assert.deepEqual(
    shouldRegenerateNotes({
      enabled: true,
      enhancedContent: "",
      generatedHash: "h",
      hashOf: () => "h",
    }),
    { regenerate: false, reason: "no-notes" }
  );
});

test("whitespace is not notes", async () => {
  const { shouldRegenerateNotes } = await load();

  assert.deepEqual(
    shouldRegenerateNotes({
      enabled: true,
      enhancedContent: "   \n  ",
      generatedHash: "h",
      hashOf: () => "h",
    }),
    { regenerate: false, reason: "no-notes" }
  );
});

test("null notes are treated as no notes", async () => {
  const { shouldRegenerateNotes } = await load();

  assert.deepEqual(
    shouldRegenerateNotes({
      enabled: true,
      enhancedContent: null,
      generatedHash: "h",
      hashOf: () => "h",
    }),
    { regenerate: false, reason: "no-notes" }
  );
});

test("notes we did not generate are left alone", async () => {
  const { shouldRegenerateNotes } = await load();

  assert.deepEqual(
    shouldRegenerateNotes({
      enabled: true,
      enhancedContent: "notes",
      generatedHash: null,
      hashOf: () => "h",
    }),
    { regenerate: false, reason: "unknown-provenance" }
  );
});

test("hand-edited notes are left alone", async () => {
  const { shouldRegenerateNotes } = await load();

  assert.deepEqual(
    shouldRegenerateNotes({
      enabled: true,
      enhancedContent: "notes",
      generatedHash: "h",
      hashOf: () => "different",
    }),
    { regenerate: false, reason: "user-edited" }
  );
});

test("untouched generated notes regenerate", async () => {
  const { shouldRegenerateNotes } = await load();

  assert.deepEqual(
    shouldRegenerateNotes({
      enabled: true,
      enhancedContent: "notes",
      generatedHash: "h",
      hashOf: () => "h",
    }),
    { regenerate: true, reason: "regenerate" }
  );
});

test("an absent setting means enabled, matching main's AUTO_REGENERATE_NOTES !== false", async () => {
  const { shouldRegenerateNotes } = await load();

  assert.deepEqual(
    shouldRegenerateNotes({
      enhancedContent: "notes",
      generatedHash: "h",
      hashOf: () => "h",
    }),
    { regenerate: true, reason: "regenerate" }
  );
});

test("the setting wins over a hand edit", async () => {
  const { shouldRegenerateNotes } = await load();

  assert.deepEqual(
    shouldRegenerateNotes({
      enabled: false,
      enhancedContent: "notes",
      generatedHash: "h",
      hashOf: () => "different",
    }),
    { regenerate: false, reason: "disabled" }
  );
});

test("no notes wins over unknown provenance", async () => {
  const { shouldRegenerateNotes } = await load();

  assert.deepEqual(
    shouldRegenerateNotes({
      enabled: true,
      enhancedContent: "",
      generatedHash: null,
      hashOf: () => "h",
    }),
    { regenerate: false, reason: "no-notes" }
  );
});
